# Generated by Django 2.2.6 on 2019-10-22 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='Text')),
                ('checked', models.BooleanField(default=False, verbose_name='Checked')),
                ('checked_date', models.DateTimeField(blank=True, default=None)),
                ('creation_date', models.DateTimeField()),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_list_app.List', verbose_name='List')),
            ],
        ),
    ]
